import type { Metadata } from "next"
import { M_PLUS_1_Code } from "next/font/google"
import { cn } from "@/registry/new-york/lib/utils"

import "./globals.css"

const mPlusFont = M_PLUS_1_Code({
  variable: "--font-m-plus-1-code",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = Readonly<{
  children: React.ReactNode
}>

export default function RootLayout(props: Props) {
  return (
    <html lang="en" className="dark">
      <body className={cn(mPlusFont.variable, "dark font-mono antialiased")}>
        {props.children}
      </body>
    </html>
  )
}
